name: 'Deploy stage'
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Install
      run: |
          sudo apt install azure-cli
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Publish
      run: dotnet publish
    - name: Create container
      run: docker build -t peturssonstefan/dawn .
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Push  
      run: 	|
          docker push peturssonstefan/dawn:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az container create --name dawn --image peturssonstefan/dawn --ip-address public --resource-group primary
          az container restart --name dawn --resource-group primary
